Can add and edit forumurl to workflow
dockstore/dockstore-ui2 pull request #1082
Opened 2020-09-30 20:23 UTC by nrzhao4

- frontend changes for [3739](https://github.com/dockstore/dockstore/issues/3739)
- discussion link appears in workflow info-tab
![Screen Shot 2020-09-30 at 4 20 05 PM](https://user-images.githubusercontent.com/50606789/94735691-25600100-0339-11eb-8856-856ab5ee7ce6.png)
- the link can be edited by owner
![Screen Shot 2020-09-30 at 4 16 58 PM](https://user-images.githubusercontent.com/50606789/94735765-3ad52b00-0339-11eb-9cf8-f5182f574783.png)

2020-09-30 20:25 UTC, nrzhao4 commented
Also, not sure about the design for the case where there is no forumUrl and an Add button is displayed. Currently it falls in line with the other Edit buttons.
<img width="769" alt="Screen Shot 2020-09-30 at 2 26 38 PM" src="https://user-images.githubusercontent.com/50606789/94735946-7d970300-0339-11eb-82ec-5adf5b6ab52f.png">
Don't know if it should lined with the checker flow Add button, or if the add checker flow button should be moved in line with the rest of the buttons

2020-10-01 14:02 UTC, denis-yuen reviewed
Watching discussion, I have an opinion but was curious what others thought

2020-10-01 16:46 UTC, NatalieEO commented
> Watching discussion, I have an opinion but was curious what others thought

I think I would prefer that all the buttons be where the +Add checker workflow button is. When the whole box is too big, the other ones are awkwardly far away (imo)

2020-10-01 16:48 UTC, coverbeck commented on src/app/workflow/info-tab/info-tab.component.html
> +                    type="text"
The type should ideally be `url`. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

But we don't use this anywhere else, so it's worth checking how it behaves. If it works, I don't think you need minLength. If you do keep minLength, it should be at least 7 (http://).

2020-10-01 16:48 UTC, coverbeck commented on src/app/workflow/info-tab/info-tab.component.html
> +                    fxFlexOffset="4px"
Ideally no pixels, but the pattern already exists, so I guess you'd have to change it everywhere on the form. :( Don't bother, unless Gary pushes for it.

2020-10-01 16:48 UTC, coverbeck commented on src/app/workflow/info-tab/info-tab.component.html
> -  <mat-card class="mt-3" *ngIf="workflow && workflow?.mode !== WorkflowType.ModeEnum.STUB && selectedVersion">
Did you remove this on purpose?

2020-10-01 16:51 UTC, coverbeck commented
> > Watching discussion, I have an opinion but was curious what others thought
> 
> I think I would prefer that all the buttons be where the +Add checker workflow button is. When the whole box is too big, the other ones are awkwardly far away (imo)

I think the buttons should all be aligned.

On whether right-most aligned or left-aligned, I could go either way. Making it left-aligned would be trickier, although not insurmountable, because the length of the text will vary.

2020-10-05 16:38 UTC, nrzhao4 commented
> > > Watching discussion, I have an opinion but was curious what others thought
> > 
> > 
> > I think I would prefer that all the buttons be where the +Add checker workflow button is. When the whole box is too big, the other ones are awkwardly far away (imo)
> 
> I think the buttons should all be aligned.
> 
> On whether right-most aligned or left-aligned, I could go either way. Making it left-aligned would be trickier, although not insurmountable, because the length of the text will vary.

For now I've made it right aligned
![image](https://user-images.githubusercontent.com/50606789/95107261-aa676380-0707-11eb-8d33-ccb3fafabeaa.png)

2020-10-05 18:18 UTC, Ldcabansay commented
On the alignment thing, I don't have a strong opinion. I feel like for the fields with values (like paths), it makes sense to right align them. It does look a bit odd to me when the blank fields (checker and discussion forum) are right aligned though, a bit too much dead space, but yeah no strong opinion.

2020-10-05 19:02 UTC, denis-yuen approved these changes

2020-10-08 04:47 UTC, wshands approved these changes

2020-10-08 16:19 UTC, NatalieEO approved these changes

2020-10-08 22:06 UTC, Ldcabansay approved these changes

2020-10-14 20:20 UTC, coverbeck requested changes

2020-10-14 20:20 UTC, coverbeck commented on src/app/workflow/info-tab/info-tab.service.ts
> +          console.log(refreshResponse);
Please remove this line.

2020-10-23 00:29 UTC, coverbeck approved these changes

2020-10-23 17:27 UTC, merged