fix/3014/toolSeachPageName
dockstore/dockstore-ui2 pull request #1090
Opened 2020-10-16 19:10 UTC by nrzhao4

Fixes issue [#3014](https://github.com/dockstore/dockstore/issues/3014).

Sorting workflows by name was actually broken too, the function tried to sort by `workflow.name` which is not defined. 

Added a property in `search-entry-table.ts` to define whether the table is showing Tools or Workflows, and passes this info as a parameter to the sort function. If the table is displaying tools it will sort using `tool.namespace` (previously sorting by `tool.name`) and if displaying workflows, it will sort by `workflow.organization` to get the desired sort results.

2020-10-16 19:38 UTC, garyluu requested changes

2020-10-16 19:38 UTC, garyluu commented on src/app/search/state/search.service.ts
> +    entryType: string
make the type `'tool' | 'workflow'`

2020-10-16 19:38 UTC, garyluu commented on src/app/search/state/search.service.ts
> +      attribute = 'namespace';
should be tool_path and full_workflow_path instead of namespace and organization (though I suppose that will all change once the index is redone)

2020-10-16 19:38 UTC, garyluu commented on src/app/search/search-entry-table.ts
> +    private entryType: string
just use an abstract constant. See my-entry.ts's pageName

2020-10-16 20:34 UTC, garyluu commented on src/app/search/state/search.service.ts
> +    // For sorting workflows by name, sort organization property
Change comment

2020-10-16 20:34 UTC, garyluu commented on src/app/search/state/search.service.spec.ts
> +    expect(searchService.compareAttributes(a, b, 'starredUsers', 'asc', 'workflow')).toEqual(-1);
add a simple test

2020-10-21 19:54 UTC, coverbeck approved these changes

2020-10-22 16:27 UTC, wshands approved these changes

2020-10-22 17:44 UTC, denis-yuen approved these changes

2020-10-22 18:54 UTC, garyluu approved these changes

2020-10-22 19:54 UTC, merged