Redesign of the starred pages
dockstore/dockstore-ui2 pull request #1297
Opened 2021-07-06 01:43 UTC by e34lin

Not completely done the redesign but would appreciate any feedback or guidance.

Notes:
- Need help with the colours of each tab
- Not able to get the verified tag
- Collection length for organizations returns 0 
- Services currently show up under the workflows tab --> created a ticket for that already

2021-07-06 19:11 UTC, garyluu commented
> * Need help with the colours of each tab

See https://dev.dockstore.net/search?entryType=workflows&searchMode=files for example on how to apply it. might need to refactor a bit and make a global style for the workflow, tool, and service color as I don't think they're part of the original palette.

> * Not able to get the verified tag

I think this is worth creating a separate issue for. seems /api/users/starredWorkflows and such doesn't return versions which is used to calculated whether the entry is verified 

> * Collection length for organizations returns 0

CollectionLength is transient, going to need to modify the endpoint and set it manually. Search "setCollectionsLength" in dockstore/dockstore to see how it's set. Also probably worth creating another issue for.

> * Services currently show up under the workflows tab --> created a ticket for that already

👍

2021-07-06 19:34 UTC, denis-yuen commented
Probably worth posting a few screenshots of how this ends up looking.

2021-07-06 19:41 UTC, e34lin commented
How it currently looks like: 
<img width="1180" alt="Screen Shot 2021-07-06 at 3 40 28 PM" src="https://user-images.githubusercontent.com/65895867/124657470-89879680-de70-11eb-89ff-41e100903493.png">
<img width="1160" alt="Screen Shot 2021-07-06 at 3 41 00 PM" src="https://user-images.githubusercontent.com/65895867/124657509-93a99500-de70-11eb-802f-b634aab696ad.png">
<img width="1180" alt="Screen Shot 2021-07-06 at 3 41 32 PM" src="https://user-images.githubusercontent.com/65895867/124657562-a623ce80-de70-11eb-8723-4b82086d4ac8.png">

2021-07-06 20:05 UTC, garyluu requested changes
Getting horizontal (and some vertical scroll bars) when I test this out locally.

Minimize commented out code (especially since there's no explanation)

2021-07-06 20:05 UTC, garyluu commented on src/app/starredentries/starredentries.component.html
> +              </mat-card>
this looks copy pasted.  "Limited duplicate code" of https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist

Create a new tiny component if necessary

2021-07-07 16:11 UTC, coverbeck reviewed
I'm going to wait until Gary's comments are addressed before doing a more in-depth review.

Also, it would be useful, to me at least, to know what you're changing, feature-wise via the PR description, and/or a link to the ticket. Your screenshots are great, but it's hard for me to know what in the UI you are changing compared to the way it is without actually trying it out.

2021-07-08 17:44 UTC, e34lin commented
> I'm going to wait until Gary's comments are addressed before doing a more in-depth review.
> 
> Also, it would be useful, to me at least, to know what you're changing, feature-wise via the PR description, and/or a link to the ticket. Your screenshots are great, but it's hard for me to know what in the UI you are changing compared to the way it is without actually trying it out.

Yup, that makes sense. I'll make sure to include that next time. But here is the link to the ticket: https://ucsc-cgl.atlassian.net/browse/SEAB-2905.

2021-07-14 19:52 UTC, denis-yuen reviewed
re-request review when appropriate

2021-07-29 18:40 UTC, e34lin commented
I created tickets for both the verified tag, and collection length so they still don't work in my current PR. I was able to get the colours for each tab to work and there shouldn't be any horizontal or vertical scroll bars anymore.  

This is how it currently looks like:
<img width="1036" alt="Screen Shot 2021-07-29 at 1 52 50 PM" src="https://user-images.githubusercontent.com/65895867/127547409-ded74d7f-a705-4da8-948e-b1dc00d67ffc.png">
<img width="1031" alt="Screen Shot 2021-07-29 at 1 52 56 PM" src="https://user-images.githubusercontent.com/65895867/127547420-042e8699-adce-450c-a321-41421ae1acfe.png">
<img width="1293" alt="Screen Shot 2021-07-29 at 1 53 09 PM" src="https://user-images.githubusercontent.com/65895867/127547422-9f761876-56ad-4a9f-9248-e32a4cba3bbe.png">

2021-07-29 20:23 UTC, garyluu reviewed
Lots of unrelated changes in the PR. Not sure what's up with GitHub. I forked your branch and rebased with develop. Check if https://github.com/dockstore/dockstore-ui2/pull/1320 has the changes you want. Probably work off of that.

2021-07-29 20:58 UTC, e34lin commented
> Lots of unrelated changes in the PR. Not sure what's up with GitHub. I forked your branch and rebased with develop. Check if #1320 has the changes you want. Probably work off of that.

Yup thank you! Will request review off of that branch.

2021-08-02 18:17 UTC, coverbeck reviewed
Seems like this should be closed in favor of #1320, right? Just making sure -- not going to review unless I get confirmation.

2021-08-03 15:39 UTC, denis-yuen reviewed
ditto

2021-08-04 16:50 UTC, e34lin commented
> Seems like this should be closed in favor of #1320, right? Just making sure -- not going to review unless I get confirmation.

yup, will be closing this now.

2021-08-04 16:50 UTC, closed without merging