CLI Quick Start Guide Headers and Style Fixes
dockstore/dockstore-ui2 pull request #1439
Opened 2022-01-26 17:29 UTC by KimberleyChong

**Description**
JIRA: [Dock-2022](https://ucsc-cgl.atlassian.net/browse/DOCK-2022?atlOrigin=eyJpIjoiN2Y5ZTZkYzZjMjdiNDRhMjg3N2FjNWFiNDhkYTliNzIiLCJwIjoiaiJ9)

Ticket states 2 bugs:
- "Part 2" appears twice
- Part 1 has different style compared to Part 2 (3,4,5.. etc.) 

### Without Changes:
### Repeated Part 2:
![image](https://user-images.githubusercontent.com/97123241/151183872-f19368af-5bd0-4720-9dce-77a32d6c5409.png)

### Mismatched Styles:
- Part 1 is font Gotham, Part 2 is Roboto

![image](https://user-images.githubusercontent.com/97123241/151183929-a4bee03c-1640-430f-8e2d-a3c6f9992782.png)

### With Changes:
- Part numbers are corrected
- Style matches Part 1 (changed font from Roboto to Gotham)

![image](https://user-images.githubusercontent.com/97123241/151183988-020a55b2-e081-4a05-be66-a5d5d8dcd6b9.png)

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [ ] Check that your code compiles by running `npm run build`
- [ ] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [ ] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [ ] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [ ] Do not use cookies, although this may change in the future
- [ ] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [ ] Do due diligence on new 3rd party libraries, checking for CVEs
- [ ] Don't allow user-uploaded images to be served from the Dockstore domain

2022-01-26 18:19 UTC, coverbeck approved these changes

2022-01-26 18:21 UTC, denis-yuen approved these changes
Screenshots are very thorough and helpful

2022-01-26 20:34 UTC, NatalieEO approved these changes

2022-01-26 22:33 UTC, garyluu requested changes
Looks like in the mockups most of the fonts as far as I can tell is Roboto. Might need to reword the issue to "Consistent font".  In other words, globally find and remove all mentions of gotham.

2022-01-27 15:49 UTC, KimberleyChong commented
**Update:** 
- Removed all mentions of Gotham, I had a look around the website and couldn't find any other visual instances of it on any other pages so it doesn't look like there will be a lot affected

![image](https://user-images.githubusercontent.com/97123241/151380984-d4ed1ffe-e9c5-47af-b103-6e6d9631acf0.png)

- The Quick Start page is now all in Roboto and looks like this:

![image](https://user-images.githubusercontent.com/97123241/151380939-edb2418b-93de-4306-90a6-04791bf0336b.png)

2022-01-27 18:26 UTC, merged