Update README for devs
dockstore/dockstore-ui2 pull request #1557
Opened 2022-06-15 00:33 UTC by aofarrel

**Description**
This change is needed because I installed the wrong version of Angular seven times.

**Issue**
N/A

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain

2022-06-15 00:36 UTC, aofarrel commented
As you may have noticed from the `OS: darwin x64` line, I'm on a Mac, so the Angular output might need to be linuxafied.

2022-06-15 14:20 UTC, denis-yuen approved these changes
thanks!

2022-06-15 14:32 UTC, kathy-t approved these changes

2022-06-15 17:13 UTC, coverbeck requested changes
I appreciate this PR -- thanks for taking the time! Sorry for all the feedback on almost every line.

But the whole global Angular thing was before we understood how to do things via package.json and a local Angular. We updated the code but never updated the README.md. If we keep references to the global Angular in here, it will quickly get out of date again, as Angular releases new versions once or twice a year. We should just remove all refs to global Angular.

2022-06-15 17:13 UTC, coverbeck commented on README.md
> +$npm i -g @angular/cli@13.2.2
We should just remove this entirely, and rely on the Angular installed via package.json.

2022-06-15 17:13 UTC, coverbeck commented on README.md
> +
I would remove this whole section, starting with line 77

2022-06-15 18:14 UTC, aofarrel commented
@coverbeck 

> But the whole global Angular thing was before we understood how to do things via package.json and a local Angular. 

I'm getting the feeling I am not part of this "we" because what I put in this readme is what I actually did 🙃

It might be best to have someone who actually understands what is going on update this readme...

2022-06-15 18:15 UTC, aofarrel commented on README.md
> +To ensure the correct dependencies are installed, run `npm install check-dependencies --save-dev` for good measure.
`npm ci` does work on my machine, but iirc, I had to also check the dependencies in addition to doing that.

2022-06-15 20:13 UTC, coverbeck commented
> @coverbeck
> 
> I'm getting the feeling I am not part of this "we" because what I put in this readme is what I actually did 🙃

I was referring the to the dev team at the time who worked on updating the package.json. No insult intended.

When you run `npm run start`, you are doing `"npx ng serve --proxy-config=proxy.conf.json` which doesn't use the global Angular. So although you installed the global Angular and things then worked, having the global Angular installed or not should be irrelevant.

2023-09-13 23:28 UTC, closed without merging

2023-09-13 23:28 UTC, aofarrel commented
@coverbeck has since updated the readme, which I followed for a fresh installation with ease. It's much better than what I have in this PR.