Updated Funding Page
dockstore/dockstore-ui2 pull request #1706
Opened 2023-02-09 21:09 UTC by KimberleyChong

**Description**
Updates to the funding page:

- New funders: Amazon and NHGRI
- Separation of "Current" and "Previous" funders
- Overall UI refresh

**Before:**
![old_fundingpage](https://user-images.githubusercontent.com/97123241/217929176-e97d3844-903b-4319-bff0-6095790aaf47.png)

**After:**
![new_fundingpage](https://user-images.githubusercontent.com/97123241/217929220-a76c6e39-7b4e-426e-83dd-e755445bb715.png)

Amazon and NHGRI are also added as Funders on the About page:
![image](https://user-images.githubusercontent.com/97123241/217938963-ffcb4690-63b3-4c56-bd68-bd93b2a09576.png)

**Review Instructions**
Ensure information looks correct

**Issue**
[DOCK-2310](https://ucsc-cgl.atlassian.net/browse/DOCK-2310)
[GitHub Issue
](https://github.com/dockstore/dockstore/issues/5328)
**Security**
If there are any concerns that require extra attention from the security team, highlight them here.

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [ ] Check that your code compiles by running `npm run build`
- [ ] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [ ] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [ ] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [ ] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [ ] Do not use cookies, although this may change in the future
- [ ] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [ ] Do due diligence on new 3rd party libraries, checking for CVEs
- [ ] Don't allow user-uploaded images to be served from the Dockstore domain
- [ ] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.
- [ ] Check whether this PR disables tests. If it legitimately needs to disable a test, create a new ticket to re-enable it in a specific milestone.

2023-02-10 14:47 UTC, kathy-t approved these changes

2023-02-10 14:47 UTC, kathy-t commented on src/app/funding/funding.component.html
> +    <div *ngFor="let section of fundingDisplay" class="">
empty class

2023-02-10 15:16 UTC, denis-yuen commented
> I can't request a review from @bvizzier for some reason... maybe permissions?

think we centralised permissions through the teams at some point and @bvizzier was left out, re-adding

2023-02-10 15:19 UTC, denis-yuen commented
> Funders no longer fit on one line... (let me know if yo have any thoughts on this) Shrinking the size makes them look microscopic

AWS and genome canada look too close, as if almost related to each other. Maybe we could use actual text on a second line for BD Catalyst. I don't know if that will be enough to get things on one line

2023-02-10 15:20 UTC, denis-yuen reviewed
one thing to experiment with

2023-02-10 15:37 UTC, KimberleyChong commented
> one thing to experiment with

Okay, I shrank both the padding and images, better now (just a little smaller...):
![image](https://user-images.githubusercontent.com/97123241/218131680-2b0d8b33-ac64-4177-955c-9126ebb91c51.png)

2023-02-10 15:58 UTC, denis-yuen commented
Thanks!
Now, the fact that the three NIH funders are not consecutive and have different sized "NIH" badges makes me feel a little funny, but I don't know if fixing it is going overboard :thinking:

2023-02-10 16:07 UTC, KimberleyChong commented
> Now, the fact that the three NIH funders are not consecutive and have different sized "NIH" badges makes me feel a little funny, but I don't know if fixing it is going overboard

Unfortunately each one is proportioned differently... but I have an idea 😉

2023-02-10 16:49 UTC, KimberleyChong commented
> Now, the fact that the three NIH funders are not consecutive and have different sized "NIH" badges makes me feel a little funny, but I don't know if fixing it is going overboard
```
// Normalize image sizes for NIH logos
.funders[alt="NIH Logo"], .funders[alt="BISTI Logo"], .funders[alt="NHGRI Logo"] {
  height: 1.7rem;
}
```
They're  _fairly_ similar in size now
![image](https://user-images.githubusercontent.com/97123241/218144980-708b0e6f-e69f-4cd8-a4a4-95d3094fc13f.png)

2023-02-10 17:51 UTC, coverbeck approved these changes
I left one question in there; I hope it doesn't throw off the layout too much if I'm right. :)

2023-02-10 17:51 UTC, coverbeck commented on src/app/funding/funding.component.ts
> +  currentFunders: Funder[] = [this.AmazonFunder, this.GenomeCanadaFunder, this.NHGRIFunder, this.NIHFunder, this.ProvinceOfOntarioFunder];
They are no longer a current funder, correct @bvizzier ?

2023-02-10 17:54 UTC, coverbeck commented on src/app/funding/funding.component.ts
> +  currentFunders: Funder[] = [this.AmazonFunder, this.GenomeCanadaFunder, this.NHGRIFunder, this.NIHFunder, this.ProvinceOfOntarioFunder];
AWS. Sorry, It was in my mind, but I forgot to write it down.

2023-02-10 20:10 UTC, bvizzier reviewed
Please check to see if there are options to make the NIH & NHGRI logos more readable.  As previously mentioned, maybe adding a new line with different scaling?

2023-02-10 21:14 UTC, KimberleyChong commented
> Please check to see if there are options to make the NIH & NHGRI logos more readable. As previously mentioned, maybe adding a new line with different scaling?

Alright, we now have two lines with all the NIH logos together on the second row:
![image](https://user-images.githubusercontent.com/97123241/218196441-0330314e-cdf3-4847-9db1-412178dcb90f.png)

Best solution I found was to use the `slice` pipe to display the first and second halves in two rows:
https://github.com/dockstore/dockstore-ui2/blob/a1eba62926ce3bdea56aacbfcfeb43aede3d8fe5/src/app/about/about.component.html#L234

https://github.com/dockstore/dockstore-ui2/blob/a1eba62926ce3bdea56aacbfcfeb43aede3d8fe5/src/app/about/about.component.html#L239

2023-02-10 21:24 UTC, bvizzier approved these changes

2023-02-10 21:28 UTC, denis-yuen approved these changes

2023-02-10 21:31 UTC, coverbeck requested changes
Temporarily blocking until funders issue is resolved one way or another.

2023-02-10 21:31 UTC, coverbeck commented on src/app/funding/funding.component.ts
> +  currentFunders: Funder[] = [this.AmazonFunder, this.GenomeCanadaFunder, this.NHGRIFunder, this.NIHFunder, this.ProvinceOfOntarioFunder];
Sorry, what is the resolution to this? Do we keep them in currentFunders or not?

2023-02-10 21:46 UTC, KimberleyChong commented
> Sorry, what is the resolution to this? Do we keep them in currentFunders or not?

Amazon is a current funder right? @bvizzier

2023-02-10 23:06 UTC, coverbeck approved these changes

2023-02-11 02:29 UTC, svonworl approved these changes

2023-02-13 14:45 UTC, merged